version: 0.2
phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nginx
      - sudo nginx -s reload
      
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
  build:
    commands:
      - cp index.html /var/www/html/index.html
  post_build:
    commands:
      - echo Post-build phase started on `date`
artifacts:
  files:
    - '**/*'